src/Entity/Animaux.php
<?php

namespace App\Entity;

use App\Repository\AnimauxRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AnimauxRepository::class)]
class Animaux
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?bool $accepte_animaux = null;

    #[ORM\Column]
    private ?float $tarif_animaux = null;

    #[ORM\ManyToOne(inversedBy: 'animauxes')]
    private ?Gites $gite = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function isAccepteAnimaux(): ?bool
    {
        return $this->accepte_animaux;
    }

    public function setAccepteAnimaux(bool $accepte_animaux): static
    {
        $this->accepte_animaux = $accepte_animaux;

        return $this;
    }

    public function getTarifAnimaux(): ?float
    {
        return $this->tarif_animaux;
    }

    public function setTarifAnimaux(float $tarif_animaux): static
    {
        $this->tarif_animaux = $tarif_animaux;

        return $this;
    }

    public function getGite(): ?Gites
    {
        return $this->gite;
    }

    public function setGite(?Gites $gite): static
    {
        $this->gite = $gite;

        return $this;
    }
}

src/Controller/AnimauxController.php
<?php

namespace App\Controller;

use App\Entity\Animaux;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;
use App\Entity\Gites;


class AnimauxController extends AbstractController
{
    #[Route('/animaux', name: 'app_animaux')]
    public function index(): Response
    {
        return $this->render('animaux/index.html.twig', [
            'controller_name' => 'AnimauxController',
        ]);
    }


    #[Route('/animaux/add', name: 'add_animaux')]
    public function addEquipements(EntityManagerInterface $entityManager): Response
    {
        $animaux = new Animaux();
        $animaux->setAccepteAnimaux(true);
        $animaux->setTarifAnimaux(20.0);
      
        $gite = $entityManager->getRepository(Gites::class)->find(5);
        $animaux->setGite($gite);

        // Ajoutez les équipements à la base de données
        $entityManager->persist($animaux);
        $entityManager->flush();

        return $this->render('animaux/add.html.twig', [
            'controller_name' => 'animauxController',
            'adjectif' => 'ajouté',
            'animaux' => $animaux,
        ]);
    }
}

templates/animaux/add.html.twig
{% block title %}Animaux ajouté{% endblock %}

{% block body %}
    <h1>Animaux ajouté</h1>

    <p>L'animaux a été ajouté avec succès.</p>

    <dl>
        <dt>ID:</dt>
        <dd>{{ animaux.id }}</dd>

        <dt>Accepte Animaux:</dt>
        <dd>{{ animaux.accepteAnimaux ? 'Oui' : 'Non' }}</dd>

        <dt>Tarif Animaux:</dt>
        <dd>{{ animaux.tarifAnimaux }}</dd>

        {# Add more details as needed #}

        <dt>Gite:</dt>
        <dd>{{ animaux.gite ? animaux.gite.id : 'Aucun' }}</dd>
    </dl>

    <a href="{{ path('app_animaux') }}">Retour à la liste des Animaux</a>
{% endblock %}

templates/animaux/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AnimauxController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ '/Users/enzosuire/Documents/Git/Gite/src/Controller/AnimauxController.php'|file_link(0) }}">src/Controller/AnimauxController.php</a></code></li>
        <li>Your template at <code><a href="{{ '/Users/enzosuire/Documents/Git/Gite/templates/animaux/index.html.twig'|file_link(0) }}">templates/animaux/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}